# Generated by Django 5.2.6 on 2025-09-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="driver",
            name="unique_email_for_driver",
        ),
    ]
